function grid_search_gui_simple()
% シンプルで確実に動作するGUI版グリッドサーチ

    % Figure作成
    fig = figure('Position', [200 200 500 400], ...
                 'Name', '直立歩行グリッドサーチ設定', ...
                 'NumberTitle', 'off', ...
                 'MenuBar', 'none');
    
    % タイトル
    uicontrol('Style', 'text', ...
              'String', '直立歩行初期条件グリッドサーチ', ...
              'Position', [10 360 480 30], ...
              'FontSize', 14, ...
              'FontWeight', 'bold');
    
    uicontrol('Style', 'text', ...
              'String', 'q1 = 0（直立）固定、参考値: u1=-0.2, q2=0.4, u2=-0.3', ...
              'Position', [10 330 480 20], ...
              'FontSize', 10);
    
    % u1設定
    uicontrol('Style', 'text', ...
              'String', 'u1（スタンス脚角速度）:', ...
              'Position', [20 290 200 20], ...
              'HorizontalAlignment', 'left', ...
              'FontWeight', 'bold');
    
    uicontrol('Style', 'text', 'String', '最小値:', ...
              'Position', [30 260 60 20], ...
              'HorizontalAlignment', 'right');
    u1_min = uicontrol('Style', 'edit', ...
                       'String', '-0.4', ...
                       'Position', [100 260 80 25]);
    
    uicontrol('Style', 'text', 'String', '最大値:', ...
              'Position', [190 260 60 20], ...
              'HorizontalAlignment', 'right');
    u1_max = uicontrol('Style', 'edit', ...
                       'String', '0', ...
                       'Position', [260 260 80 25]);
    
    uicontrol('Style', 'text', 'String', '刻み:', ...
              'Position', [350 260 50 20], ...
              'HorizontalAlignment', 'right');
    u1_step = uicontrol('Style', 'edit', ...
                        'String', '0.05', ...
                        'Position', [410 260 60 25]);
    
    % q2設定
    uicontrol('Style', 'text', ...
              'String', 'q2（スイング脚角度）:', ...
              'Position', [20 210 200 20], ...
              'HorizontalAlignment', 'left', ...
              'FontWeight', 'bold');
    
    uicontrol('Style', 'text', 'String', '最小値:', ...
              'Position', [30 180 60 20], ...
              'HorizontalAlignment', 'right');
    q2_min = uicontrol('Style', 'edit', ...
                       'String', '0', ...
                       'Position', [100 180 80 25]);
    
    uicontrol('Style', 'text', 'String', '最大値:', ...
              'Position', [190 180 60 20], ...
              'HorizontalAlignment', 'right');
    q2_max = uicontrol('Style', 'edit', ...
                       'String', '0.6', ...
                       'Position', [260 180 80 25]);
    
    uicontrol('Style', 'text', 'String', '刻み:', ...
              'Position', [350 180 50 20], ...
              'HorizontalAlignment', 'right');
    q2_step = uicontrol('Style', 'edit', ...
                        'String', '0.05', ...
                        'Position', [410 180 60 25]);
    
    % u2設定
    uicontrol('Style', 'text', ...
              'String', 'u2（スイング脚角速度）:', ...
              'Position', [20 130 200 20], ...
              'HorizontalAlignment', 'left', ...
              'FontWeight', 'bold');
    
    uicontrol('Style', 'text', 'String', '最小値:', ...
              'Position', [30 100 60 20], ...
              'HorizontalAlignment', 'right');
    u2_min = uicontrol('Style', 'edit', ...
                       'String', '-0.5', ...
                       'Position', [100 100 80 25]);
    
    uicontrol('Style', 'text', 'String', '最大値:', ...
              'Position', [190 100 60 20], ...
              'HorizontalAlignment', 'right');
    u2_max = uicontrol('Style', 'edit', ...
                       'String', '0', ...
                       'Position', [260 100 80 25]);
    
    uicontrol('Style', 'text', 'String', '刻み:', ...
              'Position', [350 100 50 20], ...
              'HorizontalAlignment', 'right');
    u2_step = uicontrol('Style', 'edit', ...
                        'String', '0.05', ...
                        'Position', [410 100 60 25]);
    
    % ボタン
    uicontrol('Style', 'pushbutton', ...
              'String', '設定を確認', ...
              'Position', [100 40 120 35], ...
              'FontSize', 11, ...
              'Callback', @check_settings);
    
    uicontrol('Style', 'pushbutton', ...
              'String', '閉じる', ...
              'Position', [280 40 120 35], ...
              'FontSize', 11, ...
              'Callback', @(~,~) close(fig));
    
    % コールバック関数
    function check_settings(~, ~)
        % 値を取得
        vals = struct();
        vals.u1_min = str2double(get(u1_min, 'String'));
        vals.u1_max = str2double(get(u1_max, 'String'));
        vals.u1_step = str2double(get(u1_step, 'String'));
        vals.q2_min = str2double(get(q2_min, 'String'));
        vals.q2_max = str2double(get(q2_max, 'String'));
        vals.q2_step = str2double(get(q2_step, 'String'));
        vals.u2_min = str2double(get(u2_min, 'String'));
        vals.u2_max = str2double(get(u2_max, 'String'));
        vals.u2_step = str2double(get(u2_step, 'String'));
        
        % 範囲作成
        u1_range = vals.u1_min:vals.u1_step:vals.u1_max;
        q2_range = vals.q2_min:vals.q2_step:vals.q2_max;
        u2_range = vals.u2_min:vals.u2_step:vals.u2_max;
        
        % 表示
        fprintf('\n=== 設定確認 ===\n');
        fprintf('u1: %.2f から %.2f まで %.3f 刻み (%d 点)\n', ...
                vals.u1_min, vals.u1_max, vals.u1_step, length(u1_range));
        fprintf('q2: %.2f から %.2f まで %.3f 刻み (%d 点)\n', ...
                vals.q2_min, vals.q2_max, vals.q2_step, length(q2_range));
        fprintf('u2: %.2f から %.2f まで %.3f 刻み (%d 点)\n', ...
                vals.u2_min, vals.u2_max, vals.u2_step, length(u2_range));
        fprintf('総探索数: %d\n', length(u1_range)*length(q2_range)*length(u2_range));
        
        % ワークスペースに保存
        assignin('base', 'grid_search_settings', vals);
        assignin('base', 'u1_range', u1_range);
        assignin('base', 'q2_range', q2_range);
        assignin('base', 'u2_range', u2_range);
        
        fprintf('\n設定が保存されました。\n');
        fprintf('以下のコマンドでグリッドサーチを実行できます:\n');
        fprintf('>> run_grid_search_from_gui\n');
    end
end