function grid_search_upright_walker_gui()
%% Grid Search GUI for Upright Walking Initial Conditions
% GUIを使用して探索範囲を設定し、グリッドサーチを実行します

    % メインフィギュアの作成
    fig = figure('Name', '直立歩行初期条件グリッドサーチ', ...
                 'Position', [100 100 700 600], ...
                 'NumberTitle', 'off', ...
                 'MenuBar', 'none', ...
                 'Resize', 'off');
    
    % 背景色の設定
    set(fig, 'Color', [0.94 0.94 0.94]);
    
    % タイトル
    uicontrol('Style', 'text', ...
              'String', '直立歩行初期条件グリッドサーチ', ...
              'Position', [50 550 600 30], ...
              'FontSize', 16, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.94 0.94 0.94]);
    
    % サブタイトル
    uicontrol('Style', 'text', ...
              'String', 'スタンス脚は直立状態（q1 = 0.0）に固定', ...
              'Position', [50 520 600 25], ...
              'FontSize', 12, ...
              'ForegroundColor', [0.8 0 0], ...
              'BackgroundColor', [0.94 0.94 0.94]);
    
    % 参考値の表示
    uicontrol('Style', 'text', ...
              'String', '参考値（オリジナルの安定な初期条件）: q1=0.2, u1=-0.2, q2=0.4, u2=-0.3', ...
              'Position', [50 490 600 20], ...
              'FontSize', 10, ...
              'ForegroundColor', [0 0 0.8], ...
              'BackgroundColor', [0.94 0.94 0.94]);
    
    %% u1の設定パネル（スタンス脚の角速度）
    panel1 = uipanel('Title', 'u1: スタンス脚の角速度', ...
                     'Position', [50 360 600 110], ...
                     'FontSize', 12, ...
                     'FontWeight', 'bold', ...
                     'ForegroundColor', [0.8 0 0], ...
                     'BackgroundColor', [1 0.95 0.95]);
    
    uicontrol('Parent', panel1, ...
              'Style', 'text', ...
              'String', '後ろ向き（負）の値で、脚を前に振り出す速度を表します', ...
              'Position', [10 60 400 20], ...
              'FontSize', 9, ...
              'BackgroundColor', [1 0.95 0.95]);
    
    % 数値入力欄
    uicontrol('Parent', panel1, ...
              'Style', 'text', 'String', '最小値:', ...
              'Position', [20 25 60 20], ...
              'BackgroundColor', [1 0.95 0.95]);
    u1_min_edit = uicontrol('Parent', panel1, ...
                            'Style', 'edit', ...
                            'String', '-0.4', ...
                            'Position', [85 25 80 25], ...
                            'FontSize', 11);
    
    uicontrol('Parent', panel1, ...
              'Style', 'text', 'String', '最大値:', ...
              'Position', [185 25 60 20], ...
              'BackgroundColor', [1 0.95 0.95]);
    u1_max_edit = uicontrol('Parent', panel1, ...
                            'Style', 'edit', ...
                            'String', '0', ...
                            'Position', [250 25 80 25], ...
                            'FontSize', 11);
    
    uicontrol('Parent', panel1, ...
              'Style', 'text', 'String', '刻み幅:', ...
              'Position', [350 25 60 20], ...
              'BackgroundColor', [1 0.95 0.95]);
    u1_step_edit = uicontrol('Parent', panel1, ...
                             'Style', 'edit', ...
                             'String', '0.05', ...
                             'Position', [415 25 80 25], ...
                             'FontSize', 11);
    
    uicontrol('Parent', panel1, ...
              'Style', 'text', ...
              'String', '（参考: -0.2）', ...
              'Position', [510 25 80 20], ...
              'FontSize', 9, ...
              'ForegroundColor', [0 0 0.8], ...
              'BackgroundColor', [1 0.95 0.95]);
    
    %% q2の設定パネル（スイング脚の角度）
    panel2 = uipanel('Title', 'q2: スイング脚の角度', ...
                     'Position', [50 240 600 110], ...
                     'FontSize', 12, ...
                     'FontWeight', 'bold', ...
                     'ForegroundColor', [0 0 0.8], ...
                     'BackgroundColor', [0.95 0.95 1]);
    
    uicontrol('Parent', panel2, ...
              'Style', 'text', ...
              'String', 'スタンス脚に対する相対角度。正の値で前方に振り出した状態', ...
              'Position', [10 60 400 20], ...
              'FontSize', 9, ...
              'BackgroundColor', [0.95 0.95 1]);
    
    % 数値入力欄
    uicontrol('Parent', panel2, ...
              'Style', 'text', 'String', '最小値:', ...
              'Position', [20 25 60 20], ...
              'BackgroundColor', [0.95 0.95 1]);
    q2_min_edit = uicontrol('Parent', panel2, ...
                            'Style', 'edit', ...
                            'String', '0', ...
                            'Position', [85 25 80 25], ...
                            'FontSize', 11);
    
    uicontrol('Parent', panel2, ...
              'Style', 'text', 'String', '最大値:', ...
              'Position', [185 25 60 20], ...
              'BackgroundColor', [0.95 0.95 1]);
    q2_max_edit = uicontrol('Parent', panel2, ...
                            'Style', 'edit', ...
                            'String', '0.6', ...
                            'Position', [250 25 80 25], ...
                            'FontSize', 11);
    
    uicontrol('Parent', panel2, ...
              'Style', 'text', 'String', '刻み幅:', ...
              'Position', [350 25 60 20], ...
              'BackgroundColor', [0.95 0.95 1]);
    q2_step_edit = uicontrol('Parent', panel2, ...
                             'Style', 'edit', ...
                             'String', '0.05', ...
                             'Position', [415 25 80 25], ...
                             'FontSize', 11);
    
    uicontrol('Parent', panel2, ...
              'Style', 'text', ...
              'String', '（参考: 0.4）', ...
              'Position', [510 25 80 20], ...
              'FontSize', 9, ...
              'ForegroundColor', [0 0 0.8], ...
              'BackgroundColor', [0.95 0.95 1]);
    
    %% u2の設定パネル（スイング脚の角速度）
    panel3 = uipanel('Title', 'u2: スイング脚の角速度', ...
                     'Position', [50 120 600 110], ...
                     'FontSize', 12, ...
                     'FontWeight', 'bold', ...
                     'ForegroundColor', [0 0 0.8], ...
                     'BackgroundColor', [0.95 0.95 1]);
    
    uicontrol('Parent', panel3, ...
              'Style', 'text', ...
              'String', 'スイング脚の振り速度。通常は負の値（後ろに振る動き）', ...
              'Position', [10 60 400 20], ...
              'FontSize', 9, ...
              'BackgroundColor', [0.95 0.95 1]);
    
    % 数値入力欄
    uicontrol('Parent', panel3, ...
              'Style', 'text', 'String', '最小値:', ...
              'Position', [20 25 60 20], ...
              'BackgroundColor', [0.95 0.95 1]);
    u2_min_edit = uicontrol('Parent', panel3, ...
                            'Style', 'edit', ...
                            'String', '-0.5', ...
                            'Position', [85 25 80 25], ...
                            'FontSize', 11);
    
    uicontrol('Parent', panel3, ...
              'Style', 'text', 'String', '最大値:', ...
              'Position', [185 25 60 20], ...
              'BackgroundColor', [0.95 0.95 1]);
    u2_max_edit = uicontrol('Parent', panel3, ...
                            'Style', 'edit', ...
                            'String', '0', ...
                            'Position', [250 25 80 25], ...
                            'FontSize', 11);
    
    uicontrol('Parent', panel3, ...
              'Style', 'text', 'String', '刻み幅:', ...
              'Position', [350 25 60 20], ...
              'BackgroundColor', [0.95 0.95 1]);
    u2_step_edit = uicontrol('Parent', panel3, ...
                             'Style', 'edit', ...
                             'String', '0.05', ...
                             'Position', [415 25 80 25], ...
                             'FontSize', 11);
    
    uicontrol('Parent', panel3, ...
              'Style', 'text', ...
              'String', '（参考: -0.3）', ...
              'Position', [510 25 80 20], ...
              'FontSize', 9, ...
              'ForegroundColor', [0 0 0.8], ...
              'BackgroundColor', [0.95 0.95 1]);
    
    %% 探索設定の表示
    info_text = uicontrol('Style', 'text', ...
                          'String', '設定を入力して「探索開始」ボタンを押してください', ...
                          'Position', [50 80 600 30], ...
                          'FontSize', 11, ...
                          'BackgroundColor', [0.94 0.94 0.94]);
    
    %% ボタン
    start_button = uicontrol('Style', 'pushbutton', ...
                            'String', '探索開始', ...
                            'Position', [150 25 120 40], ...
                            'FontSize', 12, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', [0.2 0.8 0.2], ...
                            'ForegroundColor', 'white', ...
                            'Callback', @start_search);
    
    cancel_button = uicontrol('Style', 'pushbutton', ...
                             'String', 'キャンセル', ...
                             'Position', [430 25 120 40], ...
                             'FontSize', 12, ...
                             'BackgroundColor', [0.8 0.2 0.2], ...
                             'ForegroundColor', 'white', ...
                             'Callback', @(~,~) close(fig));
    
    %% 探索開始のコールバック関数
    function start_search(~, ~)
        % 入力値の取得
        u1_min = str2double(get(u1_min_edit, 'String'));
        u1_max = str2double(get(u1_max_edit, 'String'));
        u1_step = str2double(get(u1_step_edit, 'String'));
        
        q2_min = str2double(get(q2_min_edit, 'String'));
        q2_max = str2double(get(q2_max_edit, 'String'));
        q2_step = str2double(get(q2_step_edit, 'String'));
        
        u2_min = str2double(get(u2_min_edit, 'String'));
        u2_max = str2double(get(u2_max_edit, 'String'));
        u2_step = str2double(get(u2_step_edit, 'String'));
        
        % 入力検証
        error_msg = '';
        if isnan(u1_min) || isnan(u1_max) || isnan(u1_step) || ...
           isnan(q2_min) || isnan(q2_max) || isnan(q2_step) || ...
           isnan(u2_min) || isnan(u2_max) || isnan(u2_step)
            error_msg = 'エラー: 数値を入力してください';
        elseif u1_min >= u1_max || q2_min >= q2_max || u2_min >= u2_max
            error_msg = 'エラー: 最小値は最大値より小さくしてください';
        elseif u1_step <= 0 || q2_step <= 0 || u2_step <= 0
            error_msg = 'エラー: 刻み幅は正の値にしてください';
        elseif u1_step > (u1_max - u1_min) || q2_step > (q2_max - q2_min) || u2_step > (u2_max - u2_min)
            error_msg = 'エラー: 刻み幅は範囲より小さくしてください';
        end
        
        if ~isempty(error_msg)
            set(info_text, 'String', error_msg, 'ForegroundColor', 'red');
            return;
        end
        
        % グリッドの作成
        u1_range = u1_min:u1_step:u1_max;
        q2_range = q2_min:q2_step:q2_max;
        u2_range = u2_min:u2_step:u2_max;
        
        total_combinations = length(u1_range) * length(q2_range) * length(u2_range);
        
        % 確認ダイアログ
        msg = sprintf(['探索設定:\n' ...
                      'u1: %.3f から %.3f まで %.3f 刻み (%d 点)\n' ...
                      'q2: %.3f から %.3f まで %.3f 刻み (%d 点)\n' ...
                      'u2: %.3f から %.3f まで %.3f 刻み (%d 点)\n' ...
                      '総探索数: %d 組み合わせ\n\n' ...
                      '探索を開始しますか？'], ...
                      u1_min, u1_max, u1_step, length(u1_range), ...
                      q2_min, q2_max, q2_step, length(q2_range), ...
                      u2_min, u2_max, u2_step, length(u2_range), ...
                      total_combinations);
        
        choice = questdlg(msg, '確認', 'はい', 'いいえ', 'はい');
        
        if strcmp(choice, 'はい')
            % GUIを閉じる
            close(fig);
            
            % 値をベースワークスペースに保存
            assignin('base', 'search_u1_range', u1_range);
            assignin('base', 'search_q2_range', q2_range);
            assignin('base', 'search_u2_range', u2_range);
            
            fprintf('\n探索範囲が設定されました。\n');
            fprintf('grid_search_upright_walker を実行してください。\n');
        end
    end
end