function grid_search_gui_simple()
% シンプルで確実に動作するGUI版グリッドサーチ（q1も設定可能）

    % Figure作成
    fig = figure('Position', [200 200 500 500], ...
                 'Name', '直立歩行グリッドサーチ設定', ...
                 'NumberTitle', 'off', ...
                 'MenuBar', 'none');
    
    % タイトル
    uicontrol('Style', 'text', ...
              'String', '直立歩行初期条件グリッドサーチ', ...
              'Position', [10 460 480 30], ...
              'FontSize', 14, ...
              'FontWeight', 'bold');
    
    uicontrol('Style', 'text', ...
              'String', '参考値（オリジナル）: q1=0.2, u1=-0.2, q2=0.4, u2=-0.3', ...
              'Position', [10 430 480 20], ...
              'FontSize', 10);
    
    % q1設定
    uicontrol('Style', 'text', ...
              'String', 'q1（スタンス脚角度）:', ...
              'Position', [20 390 200 20], ...
              'HorizontalAlignment', 'left', ...
              'FontWeight', 'bold', ...
              'ForegroundColor', [0.8 0 0]);
    
    uicontrol('Style', 'text', 'String', '最小値:', ...
              'Position', [30 360 60 20], ...
              'HorizontalAlignment', 'right');
    q1_min = uicontrol('Style', 'edit', ...
                       'String', '0', ...
                       'Position', [100 360 80 25], ...
                       'BackgroundColor', [1 0.95 0.95]);
    
    uicontrol('Style', 'text', 'String', '最大値:', ...
              'Position', [190 360 60 20], ...
              'HorizontalAlignment', 'right');
    q1_max = uicontrol('Style', 'edit', ...
                       'String', '0', ...
                       'Position', [260 360 80 25], ...
                       'BackgroundColor', [1 0.95 0.95]);
    
    uicontrol('Style', 'text', 'String', '刻み:', ...
              'Position', [350 360 50 20], ...
              'HorizontalAlignment', 'right');
    q1_step = uicontrol('Style', 'edit', ...
                        'String', '0.05', ...
                        'Position', [410 360 60 25], ...
                        'BackgroundColor', [1 0.95 0.95]);
    
    % u1設定
    uicontrol('Style', 'text', ...
              'String', 'u1（スタンス脚角速度）:', ...
              'Position', [20 310 200 20], ...
              'HorizontalAlignment', 'left', ...
              'FontWeight', 'bold');
    
    uicontrol('Style', 'text', 'String', '最小値:', ...
              'Position', [30 280 60 20], ...
              'HorizontalAlignment', 'right');
    u1_min = uicontrol('Style', 'edit', ...
                       'String', '-0.4', ...
                       'Position', [100 280 80 25]);
    
    uicontrol('Style', 'text', 'String', '最大値:', ...
              'Position', [190 280 60 20], ...
              'HorizontalAlignment', 'right');
    u1_max = uicontrol('Style', 'edit', ...
                       'String', '0', ...
                       'Position', [260 280 80 25]);
    
    uicontrol('Style', 'text', 'String', '刻み:', ...
              'Position', [350 280 50 20], ...
              'HorizontalAlignment', 'right');
    u1_step = uicontrol('Style', 'edit', ...
                        'String', '0.05', ...
                        'Position', [410 280 60 25]);
    
    % q2設定
    uicontrol('Style', 'text', ...
              'String', 'q2（スイング脚角度）:', ...
              'Position', [20 230 200 20], ...
              'HorizontalAlignment', 'left', ...
              'FontWeight', 'bold', ...
              'ForegroundColor', [0 0 0.8]);
    
    uicontrol('Style', 'text', 'String', '最小値:', ...
              'Position', [30 200 60 20], ...
              'HorizontalAlignment', 'right');
    q2_min = uicontrol('Style', 'edit', ...
                       'String', '0', ...
                       'Position', [100 200 80 25], ...
                       'BackgroundColor', [0.95 0.95 1]);
    
    uicontrol('Style', 'text', 'String', '最大値:', ...
              'Position', [190 200 60 20], ...
              'HorizontalAlignment', 'right');
    q2_max = uicontrol('Style', 'edit', ...
                       'String', '0.6', ...
                       'Position', [260 200 80 25], ...
                       'BackgroundColor', [0.95 0.95 1]);
    
    uicontrol('Style', 'text', 'String', '刻み:', ...
              'Position', [350 200 50 20], ...
              'HorizontalAlignment', 'right');
    q2_step = uicontrol('Style', 'edit', ...
                        'String', '0.05', ...
                        'Position', [410 200 60 25], ...
                        'BackgroundColor', [0.95 0.95 1]);
    
    % u2設定
    uicontrol('Style', 'text', ...
              'String', 'u2（スイング脚角速度）:', ...
              'Position', [20 150 200 20], ...
              'HorizontalAlignment', 'left', ...
              'FontWeight', 'bold', ...
              'ForegroundColor', [0 0 0.8]);
    
    uicontrol('Style', 'text', 'String', '最小値:', ...
              'Position', [30 120 60 20], ...
              'HorizontalAlignment', 'right');
    u2_min = uicontrol('Style', 'edit', ...
                       'String', '-0.5', ...
                       'Position', [100 120 80 25], ...
                       'BackgroundColor', [0.95 0.95 1]);
    
    uicontrol('Style', 'text', 'String', '最大値:', ...
              'Position', [190 120 60 20], ...
              'HorizontalAlignment', 'right');
    u2_max = uicontrol('Style', 'edit', ...
                       'String', '0', ...
                       'Position', [260 120 80 25], ...
                       'BackgroundColor', [0.95 0.95 1]);
    
    uicontrol('Style', 'text', 'String', '刻み:', ...
              'Position', [350 120 50 20], ...
              'HorizontalAlignment', 'right');
    u2_step = uicontrol('Style', 'edit', ...
                        'String', '0.05', ...
                        'Position', [410 120 60 25], ...
                        'BackgroundColor', [0.95 0.95 1]);
    
    % ボタン
    uicontrol('Style', 'pushbutton', ...
              'String', '設定を確認', ...
              'Position', [100 40 120 35], ...
              'FontSize', 11, ...
              'Callback', @check_settings);
    
    uicontrol('Style', 'pushbutton', ...
              'String', '閉じる', ...
              'Position', [280 40 120 35], ...
              'FontSize', 11, ...
              'Callback', @(~,~) close(fig));
    
    % コールバック関数
    function check_settings(~, ~)
        % 値を取得
        vals = struct();
        vals.q1_min = str2double(get(q1_min, 'String'));
        vals.q1_max = str2double(get(q1_max, 'String'));
        vals.q1_step = str2double(get(q1_step, 'String'));
        vals.u1_min = str2double(get(u1_min, 'String'));
        vals.u1_max = str2double(get(u1_max, 'String'));
        vals.u1_step = str2double(get(u1_step, 'String'));
        vals.q2_min = str2double(get(q2_min, 'String'));
        vals.q2_max = str2double(get(q2_max, 'String'));
        vals.q2_step = str2double(get(q2_step, 'String'));
        vals.u2_min = str2double(get(u2_min, 'String'));
        vals.u2_max = str2double(get(u2_max, 'String'));
        vals.u2_step = str2double(get(u2_step, 'String'));
        
        % 範囲作成
        q1_range = vals.q1_min:vals.q1_step:vals.q1_max;
        if isempty(q1_range)  % 最小値=最大値の場合
            q1_range = vals.q1_min;
        end
        u1_range = vals.u1_min:vals.u1_step:vals.u1_max;
        q2_range = vals.q2_min:vals.q2_step:vals.q2_max;
        u2_range = vals.u2_min:vals.u2_step:vals.u2_max;
        
        % 表示
        fprintf('\n=== 設定確認 ===\n');
        fprintf('q1: %.2f から %.2f まで %.3f 刻み (%d 点)\n', ...
                vals.q1_min, vals.q1_max, vals.q1_step, length(q1_range));
        fprintf('u1: %.2f から %.2f まで %.3f 刻み (%d 点)\n', ...
                vals.u1_min, vals.u1_max, vals.u1_step, length(u1_range));
        fprintf('q2: %.2f から %.2f まで %.3f 刻み (%d 点)\n', ...
                vals.q2_min, vals.q2_max, vals.q2_step, length(q2_range));
        fprintf('u2: %.2f から %.2f まで %.3f 刻み (%d 点)\n', ...
                vals.u2_min, vals.u2_max, vals.u2_step, length(u2_range));
        fprintf('総探索数: %d\n', length(q1_range)*length(u1_range)*length(q2_range)*length(u2_range));
        
        % ワークスペースに保存
        assignin('base', 'grid_search_settings', vals);
        assignin('base', 'q1_range', q1_range);
        assignin('base', 'u1_range', u1_range);
        assignin('base', 'q2_range', q2_range);
        assignin('base', 'u2_range', u2_range);
        
        fprintf('\n設定が保存されました。\n');
        fprintf('以下のコマンドでグリッドサーチを実行できます:\n');
        fprintf('>> run_grid_search_from_gui\n');
    end
end